### PR TITLE
Grouping docs fixes

### PR DESCRIPTION
**Pull request by gyohza**
- Grammatical adjustments - titles and filename included;
- Fixes to routes in the example.

### CODE REVIEW

**Review by bogeychan — APPROVED** [review]
Thanks for your contribution, lgtm

**Comment by fecony** [comment]
Hey @gyohza Thank you for you contribution!

I noticed you changed group filename to `docs/patterns/grouping-routes.md`. This breaks navigation in sidebar as path to that page is defined in `docs/.vitepress/config.ts`. 

Could you update it there as well or rename the group file as it was before?
The sidebar name can also be changed there if necessary.

**Comment by gyohza** [comment]
Hi, @fecony - thanks for the heads up. Just did it!

**Comment by gyohza** [comment]
Hi, @fecony - just did it. Thanks for the heads up!

**Review by fecony — APPROVED** [review]
LGTM 🪄

**Pull request merged**
