### PR TITLE
feat: add elysia-i18next to plugin list

### PR DESCRIPTION
**Pull request by eelkevdbos**

### CODE REVIEW

**Comment by Fecony** [comment]
how is title different from commit message  👀

**Comment by eelkevdbos** [comment]
I thought it to be rude not to give the PR a title, but the change is very limited and so not much more than the commit msg I'm afraid. Would you like to see something different?

**Comment by eelkevdbos** [comment]
Sorry, template error :)

**Comment by eelkevdbos** [comment]
I have fixed the title, would be happy to incorporate some more description if needed.

**Pull request merged**
